<!DOCTYPE html>

<html lang="en">
<head>
    <?php echo $this->headTitle($this->translate('MP3 Player', 'mp3'))->setAutoEscape(true); ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->setCharset('UTF-8');?>

    <style>
        html, body {
            margin: 0;
            padding: 0;
        }

        body {
            font-family: Arial, serif;
            font-size: 12px;
            font-weight: normal;
        }

        a {
            text-decoration: none;
            color: #4B598A;
        }

        table.mp3_table {
            background-color: #4B598A;
            border-collapse: collapse;
            width: 100%;
        }

        thead.mp3_thead {
            color: #FFFFFF;
            border: solid #FFFFFF 1px;
        }

        th.mp3_border, td.mp3_border, tbody.mp3_border {
            border: solid #FFFFFF 1px;
        }

        td.mp3_padding {
            padding: 5px;
        }

        table.mp3_table tr.mp3_tr:hover {
            background-color: #FBEC88;
        }

        tr.mp3_tr:nth-child(odd) {
            background-color: #FFFFFF;
        }

        tr.mp3_tr:nth-child(even) {
            background-color: #DDDDDD;
        }

        th.mp3_center, td.mp3_center {
            text-align: center;
        }

        tr.mp3_footer {
            background-color: #4B598A;
            color: #FFFFFF;
        }

        tr.mp3_footer a {
            color: #FFFFFF;
        }

        tr.mp3_nagivation a {
            text-align: left;
            color: #FFFFFF;
        }

        tr.mp3_nagivation a:hover {
            color: #FF0000;
        }

        tr.mp3_nagivation th {
            padding-left: 5px;
            float: left;
        }

        tr.mp3_search {
            background-color: #4B598A;
            color: #FFFFFF;
        }

        td.mp3_search {
            border: solid #FFFFFF 1px;
            padding-left: 5px;
        }

        input:focus {
            outline: none;
        }

        input[type=submit] {
            border: solid #4B598A 1px;
            color: #4B598A;
        }

        input[type=text] {
            border: solid #4B598A 1px;
            width: 200px;
        }

        select {
            border: solid #4B598A 1px;
        }
    </style>
</head>

<body>

<table class="mp3_table">
    <thead class="mp3_thead">
    <tr class="mp3_nagivation">
        <th>:: <a href="<?php echo $this->url('mp3-index'); ?>"><?php echo $this->translate('Home', 'mp3'); ?></a>
            <?php
            if (isset($this->dir)):
                foreach ($this->navigate(rawurldecode($this->dir)) as $key => $value):
                    echo ' :: <a href="' . $this->url('mp3-index', array('dir' => $value['url'])) . '">' . $value['text'] . '</a>';
                endforeach;
            endif;
            ?> ::
        </th>
    </tr>
    </thead>
</table>

<?php
if ($this->search):
    $this->formSubmit()->setTranslatorTextDomain('mp3');

    echo $this->form()->openTag($this->form)
    ?>

    <table class="mp3_table">
        <thead class="mp3_thead">
        <tr class="mp3_search">
            <td class="mp3_search"
                style="width: 20%;"><?php echo $this->formText($this->form->get('name')); ?> <?php echo $this->formSubmit($this->form->get('submit')); ?></td>
            <?php if ($this->flash != ''): ?>
                <td class="mp3_search"
                    style="width: 80%; color: #FBEC88; "><?php echo $this->translate($this->flash, 'mp3'); ?></td>
            <?php endif; ?>
        </tr>
        </thead>
    </table>

    <?php echo $this->form()->closeTag($this->form); endif; ?>

<table class="mp3_table">
    <thead class="mp3_thead">
    <tr>
        <th class="mp3_border mp3_center"
            style="width: 50%;"><?php echo $this->translate('Name', 'mp3'); ?>
        </th>
        <th class="mp3_border mp3_center"
            style="width: 10%;"><?php echo $this->translate('Bit Rate', 'mp3'); ?>
        </th>
        <th class="mp3_border mp3_center"
            style="width: 10%;"><?php echo $this->translate('Length', 'mp3'); ?>
        </th>
        <th class="mp3_border mp3_center"
            style="width: 10%;"><?php echo $this->translate('Size', 'mp3'); ?>
        </th>
        <th class="mp3_border mp3_center"
            style="width: 20%;"><?php echo $this->translate('Play', 'mp3'); ?>
        </th>
    </tr>
    </thead>

    <tbody class="mp3_border">
    <?php
    $array = array();

    foreach ($this->paginator as $item): $array[] = $item['type']; ?>
        <tr class="mp3_tr">
            <td class="mp3_border mp3_padding"><?php echo $this->escapeHtml($item['name']); ?></td>
            <td class="mp3_border mp3_center mp3_padding"><?php if ($item['type'] == 'file'): echo $item['bit_rate'];
                else: ?>-<?php endif; ?></td>
            <td class="mp3_border mp3_center mp3_padding"><?php if ($item['type'] == 'file'): echo $item['length'];
                else: ?>-<?php endif; ?></td>
            <td class="mp3_border mp3_center mp3_padding"><?php if ($item['type'] == 'file'): echo $this->convert($item['size']);
                else: ?>-<?php endif; ?></td>
            <td class="mp3_border mp3_center mp3_padding">
                <?php if ($item['type'] == 'dir'): ?>
                    <a href="<?php echo $this->url('mp3-index', array('dir' => $item['location'])); ?>"><?php echo $this->translate('Open', 'mp3'); ?></a>
                <?php endif; ?>

                <?php if ($item['type'] == 'file'): ?>
                    <a href="<?php echo $this->url('mp3-play-single', array('dir' => $item['location'])); ?>"><?php echo $this->translate('Play', 'mp3'); ?></a>
                    <span> | </span>
                    <a href="<?php echo $this->url('mp3-download-single', array('dir' => $item['location'])); ?>"><?php echo $this->translate('Download', 'mp3'); ?></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>

    <tr class="mp3_footer">
        <td><?php echo $this->translate('Total Results', 'mp3'); ?>: <?php echo $this->paginator->getCurrentItemCount(); ?></td>
        <td>&nbsp;</td>
        <td class="mp3_border mp3_center"><?php echo $this->total_length; ?></td>
        <td class="mp3_border mp3_center"><?php echo $this->convert($this->total_size); ?></td>
        <?php if (count($array) > '0' && !in_array('dir', $array)): ?>
            <td class="mp3_border mp3_center">
                <a href="<?php echo $this->url('mp3-play-all', array('dir' => $this->path)); ?>"><?php echo $this->translate('Play All', 'mp3'); ?></a>
                <?php if (extension_loaded('Phar')): ?>
                <span> | </span>
                <select id="download">
                    <option value="0">Select Download</option>
                    <option value="<?php echo $this->url('mp3-download-folder', array(
                        'dir'    => $this->path,
                        'format' => 'zip'
                    )); ?>">Zip
                    </option>
                    <option value="<?php echo $this->url('mp3-download-folder', array(
                        'dir'    => $this->path,
                        'format' => 'tar'
                    )); ?>">Tar
                    </option>
                    <option value="<?php echo $this->url('mp3-download-folder', array(
                        'dir'    => $this->path,
                        'format' => 'bz2'
                    )); ?>">Bz2
                    </option>
                    <option value="<?php echo $this->url('mp3-download-folder', array(
                        'dir'    => $this->path,
                        'format' => 'rar'
                    )); ?>">Rar
                    </option>
                </select>
                <?php endif; ?>
            </td>
        <?php else: ?>
            <td>&nbsp;</td>
        <?php endif; ?>
    </tr>

    <script>
        document.getElementById('download').addEventListener('change', function () {
            if (this.value != '0') {
                window.location = this.value;
            }
        }, false);
    </script>

    </tbody>
</table>

</body>
</html>
