<!DOCTYPE html>
<html lang="en">
<head>
    <?php echo $this->headTitle('MP3 Player')->setAutoEscape(true); ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->setCharset('UTF-8'); ?>

    <style>
        html, body {
            margin: 0;
            padding: 0;
        }

        body {
            font-family: Arial, serif;
            font-size: 12px;
            font-weight: normal;
        }

        a {
            text-decoration: none;
            color: #4B598A;
        }

        table.mp3_table {
            background-color: #4B598A;
            border-collapse: collapse;
            width: 100%;
        }

        thead.mp3_thead {
            color: #FFFFFF;
            border: solid #FFFFFF 1px;
        }

        th.mp3_border, td.mp3_border, tbody.mp3_border {
            border: solid #FFFFFF 1px;
        }

        td.mp3_padding {
            padding: 5px;
        }

        table.mp3_table tr.mp3_tr:hover {
            background-color: #FBEC88;
        }

        tr.mp3_tr:nth-child(odd) {
            background-color: #FFFFFF;
        }

        tr.mp3_tr:nth-child(even) {
            background-color: #DDDDDD;
        }

        th.mp3_center, td.mp3_center {
            text-align: center;
        }

        tr.mp3_footer {
            background-color: #4B598A;
            color: #FFFFFF;
        }

        tr.mp3_footer a {
            color: #FFFFFF;
        }

        tr.mp3_nagivation a {
            text-align: left;
            color: #FFFFFF;
        }

        tr.mp3_nagivation a:hover {
            color: #FF0000;
        }

        tr.mp3_nagivation th {
            padding-left: 5px;
            float: left;
        }
    </style>
</head>

<body>

<table class="mp3_table">
    <thead class="mp3_thead">
    <tr class="mp3_nagivation">
        <th>:: <a href="<?php echo $this->url('mp3-search'); ?>">Home</a>
            <?php
            foreach ($this->navigate(rawurldecode($this->dir)) as $key => $value):
                if ($value['url'] !== null) {
                    echo '<a href="' . $this->url('mp3-search', array('dir' => $value['url'])) . '">' . $value['text'] . '</a> :: ';
                } else {
                    echo $value['text'];
                }
            endforeach;
            ?> ::
        </th>
    </tr>
    </thead>
</table>

<table class="mp3_table">
    <thead class="mp3_thead">
    <tr>
        <th class="mp3_border mp3_center"
            style="width: 50%;">Name
        </th>
        <th class="mp3_border mp3_center"
            style="width: 10%;">Bit Rate
        </th>
        <th class="mp3_border mp3_center"
            style="width: 10%;">Length
        </th>
        <th class="mp3_border mp3_center"
            style="width: 10%;">Size
        </th>
        <th class="mp3_border mp3_center"
            style="width: 20%;">Play
        </th>
    </tr>
    </thead>

    <tbody class="mp3_border">
    <?php
    $dir = false;
    foreach ($this->paginator as $item):
        if ($item['type'] == 'dir'):
            $dir = true; endif; ?>
        <tr class="mp3_tr">
            <td class="mp3_border mp3_padding"><?php echo $this->escapeHtml($item['name']); ?></td>
            <td class="mp3_border mp3_center mp3_padding"><?php if ($item['type'] == 'file'): echo $item['bit_rate'];
                else: ?>-<?php endif; ?></td>
            <td class="mp3_border mp3_center mp3_padding"><?php if ($item['type'] == 'file'): echo $item['length'];
                else: ?>-<?php endif; ?></td>
            <td class="mp3_border mp3_center mp3_padding"><?php if ($item['type'] == 'file'): echo $this->convert($item['size']);
                else: ?>-<?php endif; ?></td>
            <td class="mp3_border mp3_center mp3_padding">
                <?php if ($item['type'] == 'dir'): ?>
                    <a href="<?php echo $this->url('mp3-search', array('dir' => $item['location'])); ?>">Open</a>
                <?php endif; ?>

                <?php if ($item['type'] == 'file'): ?>
                    <a href="<?php echo $this->url('mp3-play-single', array('dir' => $item['location'])); ?>">Play</a>
                    <span> | </span>
                    <a href="<?php echo $this->url('mp3-download-single', array('dir' => $item['location'])); ?>">Download</a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>

    <?php if (!$dir): ?>
        <tr class="mp3_footer">
            <td>Total Results: <?php echo $this->paginator->getCurrentItemCount(); ?></td>
            <td>&nbsp;</td>
            <td class="mp3_border mp3_center"><?php echo $this->total_length; ?></td>
            <td class="mp3_border mp3_center"><?php echo $this->convert($this->total_size); ?></td>
            <td class="mp3_border mp3_center">
                <a href="<?php echo $this->url('mp3-play-all', array('dir' => $this->path)); ?>">Play All</a>
            </td>
        </tr>
    <?php endif; ?>
    </tbody>
</table>

</body>
</html>
