<?php
/**
 * MP3 Player
 *
 * @author    Sammie S. Taunton <diemuzi@gmail.com>
 * @copyright 2014 Sammie S. Taunton
 * @license   https://github.com/diemuzi/mp3/blob/master/LICENSE License
 * @link      https://github.com/diemuzi/mp3 MP3 Player
 */

echo $this->doctype();
?>

<html lang="en">
<head>
    <?php
    echo $this->headTitle(
        $this->translate(
            'MP3 Player',
            'mp3'
        )
    );

    echo $this->headMeta()
              ->appendName(
                  'viewport',
                  'width=device-width, initial-scale=1.0'
              )
              ->setCharset('UTF-8');
    ?>

    <style>
        html, body {
            margin  : 0;
            padding : 0;
        }

        body {
            font-family : Arial, serif;
            font-size   : 12px;
            font-weight : normal;
        }

        a {
            text-decoration : none;
            color           : #4B598A;
        }

        table.mp3_table {
            background-color : #4B598A;
            border-collapse  : collapse;
            width            : 100%;
        }

        thead.mp3_thead {
            color  : #FFFFFF;
            border : solid #FFFFFF 1px;
        }

        th.mp3_border, td.mp3_border, tbody.mp3_border {
            border : solid #FFFFFF 1px;
        }

        td.mp3_padding {
            padding : 5px;
        }

        table.mp3_table tr.mp3_tr:hover {
            background-color : #FBEC88;
        }

        tr.mp3_tr:nth-child(odd) {
            background-color : #FFFFFF;
        }

        tr.mp3_tr:nth-child(even) {
            background-color : #DDDDDD;
        }

        th.mp3_center, td.mp3_center {
            text-align : center;
        }

        tr.mp3_footer {
            background-color : #4B598A;
            color            : #FFFFFF;
        }

        tr.mp3_footer a {
            color : #FFFFFF;
        }

        tr.mp3_footer a:hover {
            color : #FBEC88;
        }

        tr.mp3_nagivation a {
            text-align : left;
            color      : #FFFFFF;
        }

        tr.mp3_nagivation a:hover {
            color : #FBEC88;
        }

        tr.mp3_nagivation th {
            padding-left : 5px;
            float        : left;
        }

        tr.mp3_search {
            background-color : #4B598A;
            color            : #FFFFFF;
        }

        td.mp3_search {
            border       : solid #FFFFFF 1px;
            padding-left : 5px;
        }

        input:focus {
            outline : none;
        }

        input[type=submit] {
            border : solid #4B598A 1px;
            color  : #4B598A;
        }

        input[type=text] {
            border : solid #4B598A 1px;
            width  : 200px;
        }

        select {
            border : solid #4B598A 1px;
        }
    </style>
</head>

<body>

<table class="mp3_table">
    <thead class="mp3_thead">
    <tr class="mp3_nagivation">
        <th>
            :: <a href="<?php echo $this->url('mp3-index'); ?>">
                <?php
                echo $this->translate(
                    'Home',
                    'mp3'
                ); ?>
            </a>
            <?php
            if (isset($this->dir)):
                foreach ($this->navigate($this->dir) as $key => $value): ?>
                    ::
                    <a href="<?php
                    echo $this->url(
                        'mp3-index',
                        ['dir' => $value['url']]
                    ); ?>">
                        <?php echo $value['text']; ?>
                    </a>
                    <?php
                endforeach;
            endif;
            ?> ::
        </th>
    </tr>
    </thead>
</table>

<?php
if ($this->search):
    $this->formSubmit()
         ->setTranslatorTextDomain('mp3');

    $this->form->setAttribute(
        'action',
        $this->url('mp3-search')
    );

    echo $this->form()
              ->openTag($this->form); ?>

    <table class="mp3_table">
        <thead class="mp3_thead">
        <tr class="mp3_search">
            <td class="mp3_search"
                style="width: 20%;">
                <?php
                echo $this->formText(
                    $this->form->get('name')
                ); ?>

                <?php echo $this->formSubmit($this->form->get('submit')); ?>
            </td>
            <?php
            if ($this->flash != ''): ?>
                <td class="mp3_search"
                    style="width: 80%; color: #FBEC88; ">
                    <?php
                    echo $this->translate(
                        $this->flash,
                        'mp3'
                    ); ?>
                </td>
                <?php
            endif; ?>
        </tr>
        </thead>
    </table>

    <?php
    echo $this->form()
              ->closeTag($this->form);
endif; ?>

<table class="mp3_table">
    <thead class="mp3_thead">
    <tr>
        <?php
        foreach ([
                     'Name'     => '50%;',
                     'Bit Rate' => '10%;',
                     'Length'   => '10%;',
                     'Size'     => '10%;',
                     'Play'     => '20%;'
                 ] as $key => $value): ?>
            <th class="mp3_border mp3_center"
                style="width: <?php
                echo $value; ?>">
                <?php
                echo $this->translate(
                    $key,
                    'mp3'
                ); ?>
            </th>
            <?php
        endforeach; ?>
    </tr>
    </thead>

    <tbody class="mp3_border">
    <?php
    $array = [];

    foreach ($this->paginator as $item): $array[] = $item['type']; ?>
        <tr class="mp3_tr">
            <td class="mp3_border mp3_padding"><?php echo $item['name']; ?></td>

            <td class="mp3_border mp3_center mp3_padding">
                <?php
                if ($item['type'] == 'file'):
                    echo $item['id3']['bitRate'];
                else:
                    echo '-';
                endif; ?>
            </td>

            <td class="mp3_border mp3_center mp3_padding">
                <?php
                if ($item['type'] == 'file'):
                    echo $item['id3']['length'];
                else:
                    echo '-';
                endif; ?>
            </td>

            <td class="mp3_border mp3_center mp3_padding">
                <?php
                if ($item['type'] == 'file'):
                    echo $this->convert(
                        $item['id3']['fileSize']
                    );
                else:
                    echo '-';
                endif; ?>
            </td>

            <td class="mp3_border mp3_center mp3_padding">
                <?php
                if ($item['type'] == 'dir'): ?>
                    <a href="<?php
                    echo $this->url(
                        'mp3-index',
                        ['dir' => $item['base64']]
                    ); ?>">
                        <?php
                        echo $this->translate(
                            'Open',
                            'mp3'
                        ); ?>
                    </a>
                    <?php
                endif; ?>

                <?php
                if ($item['type'] == 'file'): ?>
                    <a href="<?php
                    echo $this->url(
                        'mp3-play-single',
                        ['dir' => $item['base64']]
                    ); ?>">
                        <?php
                        echo $this->translate(
                            'Play',
                            'mp3'
                        ); ?>
                    </a>

                    <span> | </span>

                    <a href="<?php
                    echo $this->url(
                        'mp3-download-single',
                        ['dir' => $item['base64']]
                    ); ?>">
                        <?php
                        echo $this->translate(
                            'Download',
                            'mp3'
                        ); ?>
                    </a>
                    <?php
                endif; ?>
            </td>
        </tr>
        <?php
    endforeach; ?>

    <tr class="mp3_footer">
        <td><?php
            echo $this->translate(
                'Total Results',
                'mp3'
            ); ?>
            : <?php
            echo $this->paginator->getCurrentItemCount(); ?>
        </td>

        <td>&nbsp;</td>

        <td class="mp3_border mp3_center"><?php echo $this->totalLength; ?></td>

        <td class="mp3_border mp3_center"><?php echo $this->convert($this->totalFileSize); ?></td>
        <?php
        if (count($array) > '0' && !in_array(
                'dir',
                $array
            )
        ): ?>
            <td class="mp3_border mp3_center">
                <a href="<?php
                echo $this->url(
                    'mp3-play-all',
                    ['dir' => $this->path]
                ); ?>">
                    <?php
                    echo $this->translate(
                        'Play All',
                        'mp3'
                    ); ?>
                </a>
                <?php
                if (extension_loaded('Phar')): ?>
                    <span> | </span>

                    <form style="display : inline-block;">
                        <label for="download"></label>

                        <select id="download">
                            <option value="0">
                                <?php
                                echo $this->translate(
                                    'Select Download',
                                    'mp3'
                                ); ?>
                            </option>

                            <?php
                            foreach ([
                                         'zip' => 'Zip',
                                         'tar' => 'Tar',
                                         'bz2' => 'Bz2',
                                         'rar' => 'Rar'
                                     ] as $key => $value): ?>
                                <option value="<?php
                                echo $this->url(
                                    'mp3-download-folder',
                                    [
                                        'dir'    => $this->path,
                                        'format' => $key
                                    ]
                                ); ?>">
                                    <?php
                                    echo $this->translate(
                                        $value,
                                        'mp3'
                                    ); ?>
                                </option>
                                <?php
                            endforeach; ?>
                        </select>
                    </form>
                    <?php
                endif; ?>
            </td>
            <?php
        else: ?>
            <td>&nbsp;</td>
            <?php
        endif; ?>
    </tr>

    <script>
        document.getElementById('download').addEventListener('change', function () {
            if (this.value != '0') {
                window.location = this.value;
            }
        }, false);
    </script>

    </tbody>
</table>

</body>
</html>
