language: php

php:
  - 5.5
  - 5.6

before_install:
  - wget http://cs.sensiolabs.org/get/php-cs-fixer.phar

before_script:
  - php php-cs-fixer.phar self-update
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev --no-interaction

script:
  - output=$(php php-cs-fixer.phar fix -v --dry-run .); if [[ $output ]]; then while read -r line; do echo -e "\e[00;31m$line\e[00m"; done <<< "$output"; false; fi;

notifications:
  irc:
    channels:
      - "chat.freenode.net#otwebsoft"
  email: false

matrix:
  fast_finish: true
