<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Mp3\Form\Search'                 => __DIR__ . '/src/Mp3/Form/Search.php',
    'Mp3\View\Helper\Navigate'        => __DIR__ . '/src/Mp3/View/Helper/Navigate.php',
    'Mp3\View\Helper\Convert'         => __DIR__ . '/src/Mp3/View/Helper/Convert.php',
    'Mp3\Controller\SearchController' => __DIR__ . '/src/Mp3/Controller/SearchController.php',
    'Mp3\Controller\IndexController'  => __DIR__ . '/src/Mp3/Controller/IndexController.php',
    'Mp3\Service\ServiceProvider'     => __DIR__ . '/src/Mp3/Service/ServiceProvider.php',
    'Mp3\Service\SearchInterface'     => __DIR__ . '/src/Mp3/Service/SearchInterface.php',
    'Mp3\Service\IndexInterface'      => __DIR__ . '/src/Mp3/Service/IndexInterface.php',
    'Mp3\Service\Index'               => __DIR__ . '/src/Mp3/Service/Index.php',
    'Mp3\Service\Search'              => __DIR__ . '/src/Mp3/Service/Search.php',
    'Mp3\Service\Calculate'           => __DIR__ . '/src/Mp3/Service/Calculate.php',
    'Mp3\InputFilter\Search'          => __DIR__ . '/src/Mp3/InputFilter/Search.php',
    'Mp3\Module'                      => __DIR__ . '/Module.php',
);
